-- SolarShield AI PostgreSQL Schema Definitions

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Citizens Register (Civil Identity Records)
CREATE TABLE IF NOT EXISTS citizens (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    national_id VARCHAR(50) UNIQUE NOT NULL,
    face_embedding_path VARCHAR(255) NOT NULL, -- S3 URL to stored facial vector/binary
    phone_number VARCHAR(20),
    email VARCHAR(100),
    home_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Criminal Registry (Watchlist mapping)
CREATE TABLE IF NOT EXISTS criminals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    citizen_id UUID REFERENCES citizens(id) ON DELETE CASCADE,
    alias VARCHAR(100),
    crime_category VARCHAR(100) NOT NULL, -- "Homicide", "Theft", "Assault", "Wanted Fugitive"
    threat_level VARCHAR(20) NOT NULL CHECK (threat_level IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')),
    wanted_since DATE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Registered Edge Surveillance Nodes (Cameras & Micro-controllers)
CREATE TABLE IF NOT EXISTS edge_nodes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    node_name VARCHAR(100) NOT NULL,
    mac_address VARCHAR(17) UNIQUE NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    latitude DECIMAL(9, 6) NOT NULL,
    longitude DECIMAL(9, 6) NOT NULL,
    installation_date DATE DEFAULT CURRENT_DATE,
    status VARCHAR(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOW_BATTERY', 'FAULT', 'OFFLINE')),
    public_key TEXT NOT NULL, -- RSA PEM Public key used for verifying payload digital signatures
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Incidents and Event Detections
CREATE TABLE IF NOT EXISTS alerts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    node_id UUID REFERENCES edge_nodes(id) ON DELETE SET NULL,
    alert_type VARCHAR(50) NOT NULL, -- "WEAPON", "VIOLENCE", "CRIMINAL_MATCH", "MISSING_PERSON", "LPR", "GEOFENCE_BREACH"
    threat_level VARCHAR(20) NOT NULL CHECK (threat_level IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')),
    image_url VARCHAR(255), -- Evidence screenshot path
    video_url VARCHAR(255), -- Evidence video clip path
    payload JSONB NOT NULL, -- Additional metadata: confidence scores, license plates, bounding boxes, vector similarity scores
    latitude DECIMAL(9, 6),
    longitude DECIMAL(9, 6),
    status VARCHAR(20) DEFAULT 'UNRESOLVED' CHECK (status IN ('UNRESOLVED', 'ACKNOWLEDGED', 'DISPATCHED', 'RESOLVED')),
    cryptographic_signature TEXT NOT NULL, -- Verification signature generated by the Node
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Tracked Vehicles (ALPR logs)
CREATE TABLE IF NOT EXISTS vehicles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    license_plate VARCHAR(20) NOT NULL,
    vehicle_make VARCHAR(50),
    vehicle_model VARCHAR(50),
    vehicle_color VARCHAR(30),
    owner_name VARCHAR(100),
    watchlist_status BOOLEAN DEFAULT FALSE,
    watchlist_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Evidence Chain of Custody Registry
CREATE TABLE IF NOT EXISTS evidence (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    alert_id UUID REFERENCES alerts(id) ON DELETE CASCADE,
    file_hash VARCHAR(64) NOT NULL, -- SHA-256 hash of media file
    file_size_bytes BIGINT NOT NULL,
    uploaded_by VARCHAR(100) NOT NULL, -- e.g., "node-system-service" or Officer ID
    verification_status BOOLEAN DEFAULT FALSE,
    verified_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexing for performance
CREATE INDEX IF NOT EXISTS idx_alerts_node_id ON alerts(node_id);
CREATE INDEX IF NOT EXISTS idx_alerts_type ON alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_created_at ON alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_criminals_citizen_id ON criminals(citizen_id);
CREATE INDEX IF NOT EXISTS idx_vehicles_plate ON vehicles(license_plate);
